# Generated by Django 3.2.9 on 2021-12-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='title',
            field=models.CharField(default='placeholder', max_length=255),
            preserve_default=False,
        ),
    ]
